spring:
  datasource:
    # MySQL ?? ?? (?? ?? 3306, DB ??? baseball_db)
    url: jdbc:mysql://localhost:3306/baseball_db?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: root
    password: ${DB_PASSWORD}  # <-- ?? ?? MySQL ????? ??!
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update  # ?? ? ?, Entity ????? DB ???? ?? ??
    show-sql: true      # ???? SQL ??? ??? ???
    properties:
      hibernate:
        format_sql: true # SQL ?? ??? ??? ?? ???